task_planner_app/tasks/urls.py
from users.views import LoginView
from django.urls import path, re_path
from tasks.views import *

app_name='tasks'

urlpatterns = [
    # Plain url sends user to login page.
    path('', LoginView, name='home'),

    # URLs for tasks and it's related functionalities.
    re_path('tasks/(?P<pk>\d+)', TaskDetailView.as_view(), name='task_details'),
    re_path('tasks_delete/(?P<pk>\d+)', TaskDeleteView.as_view(), name='task_delete'),
    re_path('tasks?sort=(.*)', TaskCreateView.as_view(), name='task_sort'),

    # URLs for task lists and it's related functionalities.
    re_path('lists/(?P<pk>\d+)$', TaskCreateView.as_view(), name='list_tasks'),
    re_path('lists_delete/(?P<pk>\d+)', ListDeleteView.as_view(), name='list_delete'),
    re_path('list_details/(?P<pk>\d+)$', ListDetailView.as_view(), name='list_details'),

    # URLs for task groups and it's related functionalities.
    re_path('groups/(?P<pk>\d+)$', TaskListCreateView.as_view(), name='group_list'),
    re_path('groups_delete/(?P<pk>\d+)', GroupDeleteView.as_view(), name='group_delete'),
    re_path('group_details/(?P<pk>\d+)$', GroupDetailView.as_view(), name='group_details'),
    re_path('groups_notify/(?P<pk>\d+)$', TaskGroupNotifyView.as_view(), name='group_notify'),

    # URLs for managing group members and it's related functionalities.
    re_path('group_members/(?P<pk>\d+)$', TaskGroupMembersView.as_view(), name='members_list'),
    path('group_members/promote', TaskGroupMembersView.promote, name='members_promote'),
    path('group_members/demote', TaskGroupMembersView.demote, name='members_demote'),
    path('group_members/kick', TaskGroupMembersView.kick, name='members_kick'),
    path('group_members/leave', TaskGroupMembersView.leave, name='members_leave'),
    
    # URLs for actioning notifications.
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name='notification_delete'),
    path('notification/accept/<int:notification_pk>', AcceptNotification.as_view(), name='notification_accept'),
    path('notification/decline/<int:notification_pk>', DeclineNotification.as_view(), name='notification_decline'),
    
    # URL for creating tags (not necessary if preloaded fixtures).
    path('tags/', TagCreateView.as_view(), name='tags'),
    
    # URLs for the dashboard and it's related functionalities.
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('groups/', DashboardGroups.as_view(), name='dashboard_groups'),
    path('dashboard/get_help/', get_help, name='get_help'),
]






    

task_planner_app/tasks/views/dashboard_views.py
"""Class and function views for the dashboard."""
import json
from serpapi import GoogleSearch
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic.edit import CreateView
from braces.views import LoginRequiredMixin
from tasks.filters import GroupFilter, TaskFilter
from tasks.models import Membership, Task, TaskGroup


class DashboardGroups(LoginRequiredMixin, CreateView):
    """View to create a new group from the dashboard.

    Inherits:
        LoginRequiredMixin: gives site access to signed in users.
        CreateView: gives access to Django pre-built view methods.
    """
    model = TaskGroup
    fields = ['name', 'description']
    template_name = 'dashboard_taskgroups.html'
    success_url = reverse_lazy('tasks:dashboard_groups')
    
    def get_context_data(self, **kwargs):
        """Gets the context for template rendering.

        Returns:
            Dictionary containing data needed to render variables in template.
        """
        context= super().get_context_data(**kwargs)
        groups = Membership.objects.filter(user=self.request.user, status='Active').values_list('group', flat=True)
        queryset = TaskGroup.objects.filter(id__in=groups)
        group_filter = GroupFilter(self.request.GET, queryset=queryset)
        context['group_filter'] = group_filter
        context['task_groups'] = group_filter.qs
        return context
        
    def form_valid(self, form):
        """Creates a task group object from the requested form. Creates membership object between user and group.

        Args:
            form: the Django formatted form received in the request.

        Returns:
            Redirection to group dashboard url.
        """
        if super().form_valid(form):
            curr = form.save(commit=False)
            curr.owner = self.request.user
            curr.list_group = curr
            curr.save()
            Membership.objects.get_or_create(
                user=self.request.user,
                group=curr,
                role='Moderator',
                status='Active'
            )
        return redirect(self.success_url)


class Dashboard(LoginRequiredMixin, CreateView):
    """View for displaying tasks details and integrated support system from the dashboard.
    Creates group from this view as well.

    Inherits:
        LoginRequiredMixin: gives site access to signed in users.
        CreateView: gives access to Django pre-built view methods.
    """
    model = TaskGroup
    fields = ['name', 'description']
    template_name = 'dashboard.html'
    success_url = reverse_lazy('tasks:dashboard')
        
    def get_context_data(self, **kwargs):
        """Gets the context for template rendering.

        Returns:
            Dictionary containing data needed to render variables in template.
        """
        context = super().get_context_data(**kwargs)
        user = self.request.user
        groups = Membership.objects.filter(user=user, status='Active').values_list('group', flat=True)
        tasks = Task.objects.filter(assignee=user, status__in=['To do', 'In progress'], list_group_id__in=groups).order_by('deadline')
        task_filter = TaskFilter(self.request.GET, queryset=tasks)
        context['filter'] = task_filter
        context['tasks'] = task_filter.qs
        return context
    
    def form_valid(self, form):
        """Creates a task group object from the requested form. Creates membership object between user and group.

        Args:
            form: the Django formatted form received in the request.

        Returns:
            Redirection to dashboard url.
        """
        if super().form_valid(form):
            curr = form.save(commit=False)
            curr.owner = self.request.user
            curr.list_group = curr
            curr.save()
            Membership.objects.get_or_create(
                user=self.request.user,
                group=curr,
                role='Moderator',
                status='Active'
            )
        return redirect(self.success_url)


@cache_page(60 * 15)
def get_help(request):
    """Sends a Google search request to SerpAPI.

    Args:
        request: data from HTTP request.

    Returns:
        HttpResponse with the API search data.
    """
    if request.is_ajax():
        task_id = request.GET.get('task_id', '')
        task = Task.objects.get(id=task_id)
        tags = [t.name for t in task.tags.all()]
        params = {
            'engine': 'google',
            'q': task.name + ' ' + ' '.join(tags),
            'api_key': '74d1eb93c70b7cb02803ff4ad122fb0234446f13f44c9f67ed4012d19518f5d8'
        }
        search = GoogleSearch(params)
        res = {
            'task_id': task_id,
            'search_results': search.get_dict()['organic_results'],
        }
        data = json.dumps(res)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

task_planner_app/tasks/templates/base.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% load static %}

<html data-theme="light">

<head>
  <title>3.5 Planner</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/task_template.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/show_notifications.css' %}">
</head>

{% include 'navbar.html' %}
{% include 'messages.html' %}
{% block breadcrumbs %}
    {% clear_breadcrumbs %}
{% endblock %}
<body>
    {% block content %}
      {% render_breadcrumbs 'tasks/templates/breadcrumbs.html' %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/54f931f71a.js" crossorigin="anonymous"></script>
</html>

task_planner_app/tasks/templates/breadcrumbs.html
<ul class="breadcrumb">
    {% for url, label in breadcrumbs %}
        <li>
            {% ifnotequal forloop.counter breadcrumbs_total %}
                <a href="{{ url }}">{{ label|safe }}</a>
            {% else %}
                {{ label|safe }}
            {% endifnotequal %}
            {% if not forloop.last %}
                <span class="divider">/</span>
            {% endif %}
        </li>
    {% endfor %}
</ul>

task_planner_app/tasks/templates/comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
      <button type="submit" class="btn btn-primary btn-lg">Add Comment</button>
    </div>
  </form>
{% endblock %}

task_planner_app/tasks/templates/dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_tags %}
{% load static %}

{% block content %}

{% include 'dashboard_nav.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
<body>
  <div class='container my-2'>
    <h1 style="position: aboslute; display: flex; justify-content: center;">
        Your Tasks
    </h1>
      
    {% comment %} ACCORDIAN FILTER {% endcomment %}
    <div class="accordion" id="accordionFilter">
      <div class="col-lg-push-2">
        <button class="btn btn-primary text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Filters
        </button>
      </div>
      <div id="collapseOne" class="collapse hide" aria-labelledby="headingOne" data-parent="#accordionFilter">
        <div class="card-body">
          <form method="GET">
            <div class="d-flex flex-row">
              {% for field in filter.form %}
                {% if forloop.counter == 1 %}
                  <div class="flex-col">
                    <div class="p-2">{{ field|as_crispy_field }}</div>
                {% elif forloop.counter == 4 or forloop.counter == 6 %}
                  </div>
                  <div class="flex-col">
                    <div class="p-2">{{ field|as_crispy_field }}</div>
                {% elif forloop.counter != 3 %}
                  <div class="p-2">{{ field|as_crispy_field }}</div>
                {% endif %}
              {% endfor %} 
              </div>
            </div>
            <button type="submit" class="btn btn-primary"><i class="fa-solid fa-filter"></i> Filter</button>
          </form>
        </div>
      </div>
    </div>
    
    <br>
    
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Task Group</th>
          <th scope="col">Task List</th>
          <th scope="col">Due Date</th>
          <th scope="col">Priority</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
          {% get_child_tasks task as child_tasks %}
          <tr href="" data-toggle="modal" data-target="#taskModal-{{ forloop.counter }}">
            <th scope="row">{{ forloop.counter }}</th>
            <td>
              {% if task.linked_tasks.all or child_tasks.all  %}
                <i class="fa-solid fa-link"></i>
              {% endif %}
              {{ task.name }}
            </td>
            <td>{{ task.task_list.list_group }}</td>
            <td>{{ task.task_list }}</td>
            <td>
              {% if task.deadline %}
                {{ task.deadline }}
              {% else %}
                -
              {% endif %}
            </td>
            <td>
              <span class="badge badge-{{ task.priority_display.style }}">
                {{ task.priority_display.priority }} 
              </span>
            </td>
            <td>
              <span class="badge badge-{{ task.status_display.style }}">
                {{ task.status_display.status }} 
              </span>
            </td>
            <td>
              <a href="{% url 'tasks:task_details' task.id%}"><i class="fa-solid fa-pen-to-square"></i></a>
            </td>
          </tr>
          <div class="task-modal modal fade" id="taskModal-{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="taskModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="taskModalLabel">{{task.name|capfirst}}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form request="GET">
                    <div class="d-flex row">
                      <div class="col-6">
                      
                        <p><span class="font-weight-bold">Task Points: </span>{{ task.estimation }}</p>
                        <p class="font-weight-bold">Description:</p>
                        <div class="description">
                          {{ task.description|safe|linebreaks }}
                        </div>
                        {% if task.linked_tasks.all %}
                          <p>
                            <p class="font-weight-bold">Parent Tasks:</p>
                            <ul class="list-group">
                            {% for task in task.linked_tasks.all %}
                              <a href="{% url 'tasks:task_details' task.id%}" class="list-group-item list-group-item-action">
                                  {{task.list_group}} - {{task.task_list }} - {{ task.name }}
                                  <i class="fa-solid fa-arrow-up-right-from-square float-right"></i>
                              </a>
                            {% endfor %}
                            </ul>
                          </p>
                        {% endif %}
                        {% get_child_tasks task as child_tasks %}
                        {% if child_tasks.all %}
                          <p>
                            <p class="font-weight-bold">Child Tasks:</p>
                            <ul class="list-group">
                            {% for taskdep in child_tasks.all %}
                              <a href="{% url 'tasks:task_details' taskdep.child_task.id%}" class="list-group-item list-group-item-action">
                                {{taskdep.child_task.list_group}} - {{taskdep.child_task.task_list }} - {{ taskdep.child_task.name }}
                                <i class="fa-solid fa-arrow-up-right-from-square float-right"></i>
                              </a>
                            {% endfor %}
                            </ul>
                          </p>
                        {% endif %}
                        {% get_task_comments task as task_comments %}
                        {% if task_comments.all %}
                          <p>
                            <p class="font-weight-bold">Comments:</p>
                              <div class='task-border' style='height:400px; width:500px; overflow-y:scroll;'>
                                {% for i in task_comments.all %}
                                  <div class="task-border">
                                    <div>@{{ i.user.name }} {{ i.date|date:"d/m/Y" }} </div>
                                    <div>{{ i.content }}</div>
                                  </div>
                                {% endfor %}
                            </div>
                          </p>
                        {% endif %}
                      </div>
                      <div class="container-sm col-6">
                        <div class="accordion" id="accordionTask-{{task.id}}">
                          <div class="col-lg-push-2">
                            <button id="help-btn-{{task.id}}" class="help-btn btn btn-primary" value="{{task.id}}" class="btn btn-primary text-left" type="button" data-toggle="collapse" data-target="#collapse-task-{{task.id}}" aria-expanded="true" aria-controls="collapse-task-{{task.id}}">
                              <i class="fa-solid fa-circle-info"></i> Show Related Sources
                              <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                            </button>
                          </div>
                          <div id="collapse-task-{{task.id}}" class="collapse hide" aria-labelledby="headingOne" data-parent="#accordionTask-{{task.id}}">
                            <div id="card-{{task.id}}" class="card-body">                  
                            </div>
                          </div>
                        </div>   
                      </div>
                    </div>
                  </form>
                </div>
                <div class="d-flex modal-footer justify-content-center">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </tbody>
    </table>
    
    <a class="btn btn-info" href="{% url 'view_pdf' %}">Create Task Reports</a>

  </div>
</body>
<script type="text/javascript" src="{% static 'js/dashboard.js' %}"></script>
{% endblock %}

task_planner_app/tasks/templates/dashboard_nav.html
{% load crispy_forms_tags %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard_nav.css' %}">
<body>
    <div class="sidebar">
        <span style='border-bottom: 1px solid rgba(0, 0, 0, 0.1); font-size: max(28px, 10px);'>Welcome, {{ request.user }}</span>
        <a href="#" style="color: navy;" data-toggle="modal" data-target="#createGroupModal"><i class="fa-solid fa-plus"></i> Create Group</a>
        <a href="{% url 'tasks:dashboard_groups' %}" style="color: navy;"><i class="fa-solid fa-people-group"></i> My Groups</a>
        <a href="{% url 'tasks:dashboard' %}" style="color: navy;"><i class="fa-solid fa-list-check"></i> My Tasks</a>
    </div>
    
    <div class="create-group-modal modal fade" id="createGroupModal" tabindex="-1" role="dialog" aria-labelledby="createGroupModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header" style='position: aboslute; display: flex; justify-content: center;'>
              <h5 class="modal-title" id="createGroupModalLabel">Create Task Group</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <div class="d-flex justify-content-center">
                  <button id='createbtn' type="submit" class="btn btn-primary" hidden></button>
                </div>
              </form>
            </div>
            <div class="d-flex modal-footer justify-content-center">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary" onclick="document.getElementById('createbtn').click()">Create <i class="fa-solid fa-plus"></i></i></button>
            </div>
          </div>
        </div>
    </div>
</body>

<script type="text/javascript" src="{% static 'js/dashboard_nav.js' %}"></script>

task_planner_app/tasks/templates/group_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class='container'>
    <h1 style="text-align: center;"> Delete Task Group </h1>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete the task group "<strong>{{ taskgroup }}</strong>"?
            <br>This will delete all of the lists and tasks in the group.</p>
        <input class="btn btn-danger" type="submit" value="Delete"/>
        <input class="btn btn-default" type="button" value="Go back" onclick="history.back()" 
            style="background-color:#696969; color: aliceblue;"/>
    </form>
</div>
{% endblock %}

task_planner_app/tasks/templates/navbar.html
{% load static %}
{% load custom_tags %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <img src="{% static 'images/logo.png' %}" height="50">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tasks:dashboard' %}">Dashboard</a>
      </li>
      {% comment %} <li class="nav-item">
        <a class="nav-link" href="{% url 'tasks:lists' %}">Task Lists</a>
      </li> {% endcomment %}
      {% comment %} <li class="nav-item">
        <a class="nav-link" href="{% url 'tasks:tasks' %}">Tasks</a>
      </li> {% endcomment %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profile_view' %}">Profile</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        {% show_notifications %}
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Sign up</a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>

task_planner_app/tasks/templates/task_group_base.html
{% load crispy_forms_tags %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/task_group_base.css' %}">
<body>
    <div class="sidebar">
        <span><i class="fa-solid fa-user"></i> Owner </span>
        <a href="{% url 'profile_view_with_pk' pk=taskgroup.owner.pk %}"> {% comment %} please add link to profile here {% endcomment %}
            <img style="border-radius: 50%" src="{{ taskgroup.owner.profile_image.url}}" width="30"height='30'>
            &nbsp@{{taskgroup.owner}}
        </a>
        <span><i class="fa-solid fa-person-military-pointing"></i> Moderators </span>
        {% for i in members%}
            {% if i.user != taskgroup.owner and i.role == 'Moderator' %}
                <a href="{% url 'profile_view_with_pk' pk=i.user.pk %}">
                    <img style="border-radius: 50%" src="{{i.user.profile_image.url}}" width="30"height='30'>
                    &nbsp@{{i.user}}
                </a>
            {% endif %}
        {% endfor %}
        <span><i class="fa-solid fa-person-praying"></i> Members </span>
        {% for i in members%}
            {% if i.user != taskgroup.owner and i.role == 'Member' %}
                <a href="{% url 'profile_view_with_pk' pk=i.user.pk %}">
                    <img style="border-radius: 50%" src="{{i.user.profile_image.url}}" width="30"height='30'>
                    &nbsp@{{i.user}}
                </a>
            {% endif %}
        {% endfor %}
    </div>
    <div class="sidebar2">
        <span style='border-bottom: 1px solid rgba(0, 0, 0, 0.1); font-size: max(28px, 10px);'><i class="fa-solid fa-bolt"></i> {{taskgroup.name|truncatechars:20}}</span>
        <a href="{% url 'tasks:group_notify' pk=taskgroup.pk %}"><i class="fa-solid fa-bullhorn"></i> Broadcast Notifications</a>
        <a href="{% url 'tasks:members_list' pk=taskgroup.pk %}"><i class="fa-solid fa-people-roof"></i> Manage Members</a>
        <div href="#" id="dropdown-btn"><i class="fa fa-caret-down"></i> Manage Task List</i></div>
        <div class="dropdown-container" id="dropdown-container">
            {% for list in tasklists %}
                <a href="{% url 'tasks:list_tasks' pk=list.pk %}">{{ list.name }}</a>
            {% endfor %}
        </div>
        <a href="{% url 'tasks:group_list' pk=taskgroup.pk %}"><i class="fa-solid fa-folder-plus"></i> Create Task List</a>
        <a href="{% url 'tasks:group_details' pk=taskgroup.pk %}" style="color: grey;"><i class="fa-solid fa-gear"></i> Manage Group</a>
        <a href="#" style="color: orange;" data-toggle="modal" data-target="#leaveModal"><i class="fa-solid fa-arrow-right-from-bracket"></i> Leave Group</a>
        <a href="{% url 'tasks:group_delete' pk=taskgroup.pk %}" style="color: red;"><i class="fa-solid fa-trash"></i> Delete Group</a>
    </div>
    
    <div class="leave-modal modal fade" id="leaveModal" tabindex="-1" role="dialog" aria-labelledby="leaveModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="leaveModalLabel">Are you sure you want to leave "{{ taskgroup }}"?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body d-flex modal-footer justify-content-center">
                <input hidden id='group-id' value="{{taskgroup.id}}">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="leave-btn" type="submit" class="btn btn-danger" value={{request.user.id}}><i class="fa-solid fa-arrow-right-from-bracket"></i> Leave</button>
            </div>
            <div class="d-flex modal-footer justify-content-center">
            </div>
          </div>
        </div>
    </div>
</body>
<script type="text/javascript">
    var clicked = localStorage.getItem('clicked');
    if (clicked == 'open') {
        $('#dropdown-container')[0].style.display = "block";
    } else {
        $('#dropdown-container')[0].style.display = "none";
    }
    const items = document.querySelectorAll('.sidebar2 a');
    var path = window.location.href
    items .forEach(item => {
        if(item.href === path) {
            item.classList.add('active');
        }
    });
</script>
<script type="text/javascript" src="{% static 'js/task_group_base.js' %}"></script>

task_planner_app/tasks/templates/task_list_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {% breadcrumb "Groups" "tasks:dashboard_groups" %}
    {% breadcrumb "Task Lists" "" %}
{% endblock %}

{% block content %}
{% include 'task_group_base.html' %}
<style>
  .container {
      padding: 0;
      display: block;
      margin-left: 400px;
      margin-right: 400px;
      width: auto;
  }
</style>
<body>
  <div class='container my-2'>
    {% render_breadcrumbs %}
    <h1 style='postition: aboslute; display: flex; justify-content: center'>
      Task Lists
    </h1>
      <form method="GET">
          {% csrf_token %}
          {{ myFilter.form|crispy }}
          <button type="submit" class="btn btn-primary">Filter</button>
      </form>
      <div class="row">
        <div class="col-lg-6">
          <div class="'row-lg">
            {% for i in task_lists %}
              <a class='text-decoration-none text-dark' href="{% url 'tasks:list_tasks' i.id%}">
                  <div class="task-border">
                      <div class="my-2 mx-3">
                          {{i.name}}
                          {{i.id}}
                      </div>
                  </div>
              </a>
            {% endfor %}
          </div>
        </div>
        <div class="col-lg-6">
          <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
              <button type="submit" class="btn btn-primary btn-lg">Create List</button>
            </div>
          </form>
        </div>
      </div>
    </div>
</body>
{% endblock %}